import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { AlertTriangle, CheckCircle, XCircle, Info, Copy, Sparkles } from 'lucide-react';
import { useState } from 'react';

const LangChainReport = ({ report }) => {
  const [copied, setCopied] = useState(false);

  if (!report) {
    return null;
  }

  const riskLevel = report.risk_level;
  const riskEmoji = {
    Low: '✅',
    Medium: '⚠️',
    High: '🚨',
  };

  const riskColor = {
    Low: '#10b981',
    Medium: '#f59e0b',
    High: '#ef4444',
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!report.success) {
    return (
      <div className="safety-report">
        <div className="error-section">
          <h3>
            <XCircle size={20} />
            Validation Error
          </h3>
          <p className="error-text">{report.error || 'Unknown error occurred'}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="safety-report">
      <div className="report-header">
        <div>
          <h2>
            <Sparkles size={24} style={{ marginRight: '0.5rem', display: 'inline-block', verticalAlign: 'middle' }} />
            LangChain Safety Report
          </h2>
        </div>
        <div
          className="risk-badge"
          style={{ backgroundColor: riskColor[riskLevel] + '20', color: riskColor[riskLevel] }}
        >
          <span className="risk-emoji">{riskEmoji[riskLevel]}</span>
          <span className="risk-level">Risk Level: {riskLevel}</span>
        </div>
      </div>

      {report.warnings && report.warnings.length > 0 && (
        <div className="report-section warnings-section">
          <h3>
            <AlertTriangle size={20} />
            Warnings
          </h3>
          <div className="warnings-list">
            {report.warnings.map((warning, idx) => (
              <div key={idx} className="warning-item">
                {warning}
              </div>
            ))}
          </div>
        </div>
      )}

      {report.duckdb_validation && (
        <div className="report-section">
          <h3>
            <Info size={20} />
            DuckDB Validation
          </h3>
          <div className="dry-run-info">
            <div className="info-item">
              <label>Syntax Valid:</label>
              <span>
                {report.duckdb_validation.syntax_valid ? (
                  <>
                    <CheckCircle size={16} className="success-icon" />
                    Yes
                  </>
                ) : (
                  <>
                    <XCircle size={16} className="error-icon" />
                    No
                  </>
                )}
              </span>
            </div>
            {report.duckdb_validation.dry_run_successful !== undefined && (
              <div className="info-item">
                <label>Dry Run Successful:</label>
                <span>
                  {report.duckdb_validation.dry_run_successful ? (
                    <>
                      <CheckCircle size={16} className="success-icon" />
                      Yes
                    </>
                  ) : (
                    <>
                      <XCircle size={16} className="error-icon" />
                      No
                    </>
                  )}
                </span>
              </div>
            )}
            {report.duckdb_validation.error && (
              <div className="error-text" style={{ marginTop: '1rem' }}>
                Error: {report.duckdb_validation.error}
              </div>
            )}
          </div>
        </div>
      )}

      {report.rollback_sql && (
        <div className="report-section rollback-section">
          <div className="section-header-with-action">
            <h3>Rollback Script (Generated by LangChain)</h3>
            <button
              className="copy-button"
              onClick={() => copyToClipboard(report.rollback_sql)}
              title="Copy to clipboard"
            >
              <Copy size={16} />
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <div className="code-block">
            <SyntaxHighlighter
              language="sql"
              style={vscDarkPlus}
              customStyle={{ margin: 0, borderRadius: '8px' }}
            >
              {report.rollback_sql}
            </SyntaxHighlighter>
          </div>
        </div>
      )}
    </div>
  );
};

export default LangChainReport;

